### ISSUE TITLE
More direct truthy?

### ISSUE THREAD

**Issue by Another-Coding-Nerd** [nepalez/assertion#3]
Hello

Is there a more direct way to define truthy/falsey in the code? I don't want to have a .yml file to lug around.

I like the way custom msgs are defined here: https://github.com/mynyml/nanotest

Of course, it's much more simple.

**Comment by nepalez** [comment]
@slackee I need to think. In principle, the translations could be redefined to check methods like `#truthy` and `#falsey` before calling `I18n`:

``` ruby
class IsAdult < Assertion::Base
  attribute :age, :name

  def truthy
    "#{name} is adult (age #{age})"
  end

  def falsey
    "#{name} is a child (age #{age})"
  end

  def check
    age.to_i >= 18
  end
end
```

But this seems to be messy.

**Comment by Another-Coding-Nerd** [comment]
There's no hurry. Thanks for your reply. I look forward to see what you come up with.

**Comment by nepalez** [comment]
@slackee I've added the feature above. I'm going to make some cleanups before releasing `0.2.4`. Maybe(Saturday).
