### ISSUE TITLE
remove constraint on ruby version

### ISSUE THREAD

**Issue by gregory** [nepalez/assertion#4]
Hey! 
Awesome gem :) 
Could you remove the restriction on the ruby version? 
Not sure why it's [there](https://github.com/nepalez/assertion/blob/master/assertion.gemspec#L19), but looks like versions above 1.9 [should be fine](https://github.com/nepalez/assertion/blob/master/.travis.yml#L8) no?

**Comment by nepalez** [comment]
Yeah, thank you. This was a bug
Changed
